blank_issues_enabled: false
contact_links:
  # - name: è³ªå•ãƒ»ç›¸è«‡
  #   url: https://github.com/nogikun/Gamification-for-factory/issues
  #   about: ãƒã‚°å ±å‘Šã‚„æ©Ÿèƒ½ãƒªã‚¯ã‚¨ã‚¹ãƒˆä»¥å¤–ã®è³ªå•ãƒ»ç›¸è«‡ã¯Discussionsã‚’ã”åˆ©ç”¨ãã ã•ã„ã€‚

# Issueä½œæˆæ™‚ã®ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆè¨­å®š
defaults:
  - template: "bug_report.yml"
    name: "ğŸ› ãƒã‚°å ±å‘Š"
    about: "ãƒã‚°ã‚’å ±å‘Šã™ã‚‹"
  - template: "add_feature_task.yml"
    name: "ğŸ’¡ Featureã‚¿ã‚¹ã‚¯è¨­å®š"
    about: "æ©Ÿèƒ½é–‹ç™ºã®ã‚¿ã‚¹ã‚¯ã‚’è¨­å®šã™ã‚‹"
  - template: "add_development_task.yml"
    name: "ğŸ’» Developmentã‚¿ã‚¹ã‚¯ã‚’è¨­å®šã™ã‚‹"
    about: "é–‹ç™ºã‚¿ã‚¹ã‚¯ã‚’å®šç¾©ã™ã‚‹"